### ISSUE TITLE
Package Control Support?

### ISSUE THREAD

**Issue by zquintana** [ummmmm/MivaScript#1]
When is it going to be added, should I should fork this and add it for you?

**Comment by ummmmm** [comment]
Wow, just saw this!  Sure you can fork it and add it if you would like.  Do you code in MivaScript?

**Comment by zquintana** [comment]
Yep. Checkout the project I create for MivaScript test units running through Miva Merchant https://github.com/zquintana/MvUnit. I'll fork this later to add support for Package Control.

**Comment by ummmmm** [comment]
Wow just saw this comment... Sorry! Will check it out!!
